openapi: 3.2.0
info:
  title: Insights.Api Loss of Load Probability and De-rated Margin…
  version: '1.0'
  description: Loss of load probability and de-rated margin forecast data.
servers:
- url: https://data.elexon.co.uk/bmrs/api/v1
tags:
- name: Loss of Load Probability and De-rated Margin
  description: Loss of load probability and de-rated margin forecast data.
paths:
  /lolpdrm/forecast/evolution:
    get:
      tags:
      - Loss of Load Probability and De-rated Margin
      summary: Loss of load probability and de-rated margin forecast (LOLPDRM)
      description: This endpoint has been moved to forecast/system/loss-of-load.
      parameters:
      - name: format
        in: query
        description: Response data format. Use json/xml to include metadata.
        schema:
          enum:
          - json
          - xml
          - csv
          type: string
      responses:
        '200':
          description: OK
      deprecated: true
      operationId: getLolpdrmForecastEvolution
      x-operation-id-source: derived
